######################################################################
# Automatically generated by qmake (3.1) Fri May 22 06:58:47 2026
######################################################################

TEMPLATE = app
TARGET = window-pager
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += plugin/pager.h plugin/pagerItem.h
SOURCES += plugin/pager.cpp \
           plugin/pagerItem.cpp \
           build/CMakeFiles/4.3.2/CompilerIdC/CMakeCCompilerId.c \
           build/CMakeFiles/4.3.2/CompilerIdCXX/CMakeCXXCompilerId.cpp
TRANSLATIONS += build/CMakeFiles/fetch-translations.dir/compiler_depend.ts \
                build/CMakeFiles/KF5Plasma_QCH.dir/compiler_depend.ts \
                build/CMakeFiles/pager.dir/compiler_depend.ts \
                build/CMakeFiles/uninstall.dir/compiler_depend.ts
